### PR TITLE
Update project files

### PR DESCRIPTION
**Pull request by marcoow**
Run `ember init` to bring files and dependencies up to date with the ember/ember cli versions we're using. As a consequence of this some of the code needs to be changed due to new linter rules.

This also adds a dependency on [ember-native-class-polyfill](https://github.com/pzuraq/ember-native-class-polyfill) which is needed to use native classes in Ember 3.4 and 3.5.

### CODE REVIEW

**Review by Turbo87 — COMMENTED** [review]
does this contain any breaking changes?

**Comment by marcoow** [comment]
nothing in this should be breaking as far as I can see – most of it affects the dummy app only anyway.

**Comment by Turbo87** [comment]
CI seems to disagree 😅

**Comment by marcoow** [comment]
looks like this ends up being `null` now https://github.com/simplabs/ember-cookies/blob/master/tests/unit/services/cookies-test.js#L20

**Comment by marcoow** [comment]
I think the native classes are the problem – wasn't aware those were only supported with 3.6… I'll create another PR dropping support for 3.0 and updating that to 3.4+ – there's na native class polyfill for 3.4 and 3.5

**Comment by BobrImperator** [comment]
https://github.com/simplabs/ember-cookies/pull/626#issuecomment-880824997 Adding this for reference
#626

**Review by nickschot — APPROVED** [review]

**Pull request merged**
