### PR TITLE
_filterCachedFastBootCookies: don't crash when requestPath is nully

### PR DESCRIPTION
**Pull request by lolmaus**
Ran into this issue using https://github.com/robwebdev/ember-cli-staticboot .

Added a tiny check that prevents the crash.

### CODE REVIEW

**Comment by marcoow** [comment]
Can you add a test for that as well?

**Comment by lolmaus** [comment]
Done. I've checked that the test is failing without this fix.

**Comment by lolmaus** [comment]
One of CI jobs failed randomly with:

> not ok 1 Browser "google-chrome --user-data-dir=/tmp/testem-472 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/472/tests/index.html?hidepassed" failed to connect. testem.js not loaded?

What the hell is this thing? I'm seeing it A LOT in Travis and CodeShip. :(

**Comment by marcoow** [comment]
I'm not sure what the scenario is in which this would happen.

**Comment by lolmaus** [comment]
It was just happening to me with Simple Auth on `fastboot` branch.

**Comment by marcoow** [comment]
This might be a bug elsewhere actually though (e.g. in FastBoot). When a request comes in, the request path should actually always be present as you can't really request anything without specifying a path.

**Comment by lolmaus** [comment]
Well, is there a reason not to merge this? The fix is pretty straightforward, has no implications and can protect against future issues like the one I had.

**Comment by marcoow** [comment]
The point is if this fixes the symptoms of another bug in a dependency I'm not sure it makes sense to merge it as it would hide that other bug. We should understand how the request path can ever be `null` first.

**Comment by lolmaus** [comment]
I can try latest releases of `ember-simple-auth` and `ember-cookies` to see if the problem still exists.

**Comment by lolmaus** [comment]
I've given it a look today, but turns out I no longer have the configuration that was causing the issue. It happened when I tried to make FastBoot use cookies, but I no longer do that.

Let's keep it closed until someone runs into this.

**Pull request closed without merging**
