### PR TITLE
added some guards around fastboot cookies

### PR DESCRIPTION
**Pull request by habdelra**
I saw some `Cannot read property 'indexOf' of undefined` in my fastboot error logs that i tracked down to this.

### CODE REVIEW

**Comment by ef4** [comment]
@habdelra it's somewhat ambiguous whether we should consider this a bug in [prember](github.com/ef4/prember) instead.

Almost everybody who is using fastboot at this point is using it via fastboot-express-middleware. Which has made its behavior a de-facto standard.

We are probably better off updating prember to more closely follow that behavior. In this case it's as simple as setting the path string [here](https://github.com/ef4/prember/blob/6664526e2fe47a17b79662199f62207beab72335/lib/prerender.js#L89-L92).

**Comment by habdelra** [comment]
makes sense

**Comment by habdelra** [comment]
the `fastboot.request.path` being used here does not originate from the request header. Definitely I wouldn't rule out a prember bug though...

**Comment by ef4** [comment]
The root issue here is that lots of the ecosystem assumes fastboot will be used inside express and depends on the express `request` and `response` being set on the visit options. This unfortunately ties us to express APIs even in cases where express is not involved.

For prember this particular issue is fixed via https://github.com/ef4/prember/pull/1

We can close this issue.

**Comment by marcoow** [comment]
Isn't [this](https://github.com/ember-fastboot/fastboot/blob/master/src/fastboot-request.js) what we get from `get('fastboot.request')`? It seems the `FastBootRequest` is not (should not) be tied to Express as it's in the FastBoot base package?

**Comment by ef4** [comment]
I agree that it should not, but it is. Unfortunately we are currently
leaking the full API of express request and response into the app.

**Pull request closed without merging**
