### PR TITLE
Updating dep version to fix #170

### LINKED ISSUE #170: Update ember-getowner-polyfill for babel 6.6.x support
The one dependency that you are using `ember-getowner-polyfill` has a newer version where it supports a new version of babel. This is needed as I am see deprecation warning in my ember app

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least 
ember-cli-babel 6.6. Version 5.2.8 located: cf2-cli -> ember-cookies -> 
ember-getowner-polyfill -> ember-cli-babel
```

I would make a PR but not sure that is really needed

### PR DESCRIPTION
**Pull request by jrock2004**
This will update the dependency that is causing deprecation warning. This will fix #170

### CODE REVIEW

**Comment by jrock2004** [comment]
I did not change the version number of package.json as I was not sure if I should bump it to `0.3.1` or `0.4.0`

**Comment by jrock2004** [comment]
If you look at the issue that this is fixing, it seems like your plugin seems to not be pulling `2.2.0` because I am getting the following warning when I am compiling my Ember app

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least 
ember-cli-babel 6.6. Version 5.2.8 located: cf2-cli -> ember-cookies -> 
ember-getowner-polyfill -> ember-cli-babel```

So it seems like its pulling 2.1.0 or earlier of polyfill. This is why I created the PR

**Comment by marcoow** [comment]
See this:

```json
"ember-getowner-polyfill": "^1.1.0 || ^2.0.0"
```

ember-cookies allows any version from the 1.x and 2.x ranges.

**Comment by marcoow** [comment]
I'd try removing your `node_modules` - I guess `npm`/`yarn` would install the latest possible `ember-getowner-polyfill` then…

**Pull request closed without merging**
