### PR TITLE
Convert to monorepo

### PR DESCRIPTION
**Pull request by SergeAstapov**
First part of #732.

Follows [Porting an Addon to V2](https://github.com/embroider-build/embroider/blob/main/PORTING-ADDONS-TO-V2.md) guide

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@marcoow would you mind to land this to keep the ball rolling for #732? As a follow up, I'll open PR with actual v2 addon format conversion.

**Comment by marcoow** [comment]
Can we use the typical monorepo structure with something like

```
packages
  |
  - ember-cookies
  - test-app
```

? See [ember-simple-auth](http://github.com/simplabs/ember-simple-auth) for reference.

**Comment by marcoow** [comment]
Also it seems there are some unrelated changes in this as well like changing npm scripts, editorconfig, changed ignore files etc. Let's keep this strictly focused on the monorepo migration and do everything else in separate PRs – that way it's going to be much easier to keep track of what's going on.

**Comment by SergeAstapov** [comment]
> Can we use the typical monorepo structure with something like
> 
> ```
> packages
>   |
>   - ember-cookies
>   - test-app
> ```
> 
> ? See [ember-simple-auth](https://github.com/simplabs/ember-simple-auth) for reference.

this is now done.

>Also it seems there are some unrelated changes in this as well like changing npm scripts, editorconfig, changed ignore files etc.

I've reverted as many unrelated changes as it makes sense without actual monorepo changes.
Most of the changes come from extracting dummy app into `test-app` package from the app, so some files like `.eslintrc.js` got copied, `.editorconfig` kept in the root (to apply to the repo) and copied to `/packages/test-app` (so the test app is close to the stock ember-cli app blueprint).

if you think it makes sense to go more granular, I can split this into two separate PRs:
* one PR would *only* introduce packages/

**Comment by SergeAstapov** [comment]
*EDIT:* @marcoow opened #740 instead to only convert to monorepo to simplify review.
This PR was trying to convert to monrepo and extra test-app from the add-ons dummy app and that caused most of the changes in GitHub.

will create a follow up PR to extract test-app once #740 gets in.

**Pull request closed without merging**
